{% set name = "cellrank" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd6b1cc6a015df119dd8bfcd1129e86ee6aa871121aeeb3d1c1f42c71bd2215b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - anndata >=0.8
    - docrep >=0.3.0
    - joblib >=0.13.1
    - matplotlib-base >=3.5.0
    - networkx >=2.2
    - numba >=0.51.0,!=0.57.0
    - numpy >=1.17.0
    - pandas >=1.5.0
    - pygam >=0.8.0
    - pygpcca >=1.0.4
    - scanpy >=1.7.2
    - scikit-learn >=0.24.0
    - scipy >=1.2.0
    - scvelo >=0.2.5
    - seaborn >=0.10.0
    - wrapt >=1.12.1

test:
  imports:
    - cellrank

about:
  home: https://github.com/theislab/cellrank
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Dynamics from multi-view single-cell data
  description: |
    CellRank is a modular framework to study cellular dynamics based on Markov state modeling of
    multi-view single-cell data.
  doc_url: https://cellrank.readthedocs.io
  dev_url: https://github.com/theislab/cellrank

extra:
  recipe-maintainers:
    - michalk8
    - WeilerP
