context:
  name: cellrank
  version: 2.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: f982f4d58e66f648dfed6cbc2fe6cceb95d12d65fc24b90f509ad3343a94f126

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - anndata >=0.11
    - docrep >=0.3
    - joblib >=1.4
    - matplotlib-base >=3.9
    - networkx >=3.4
    - numba >=0.60
    - numpy >=2
    - pandas >=2.2
    - pygam >=0.10
    - pygpcca >=1.0.4
    - rich >=13
    - scanpy >=1.11
    - scikit-learn >=1.6
    - scipy >=1.14
    - seaborn >=0.13
    - session-info2 >=0.2
    - wrapt >=1.16
tests:
  - python:
      imports:
        - cellrank
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/theislab/cellrank
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Dynamics from multi-view single-cell data
  description: |
    CellRank is a modular framework to study cellular dynamics based on Markov state modeling of
    multi-view single-cell data.
  documentation: https://cellrank.readthedocs.io
  repository: https://github.com/theislab/cellrank

extra:
  recipe-maintainers:
    - michalk8
    - WeilerP
    - Marius1311
